#############################################################################
# Makefile for building: Kulki
# Generated by qmake (2.01a) (Qt 4.8.1) on: Sun Jun 10 02:28:43 2012
# Project:  Kulki.pro
# Template: app
# Command: /home/juggler/QtSDK/Desktop/Qt/4.8.1/gcc/bin/qmake -spec ../Desktop/Qt/4.8.1/gcc/mkspecs/linux-g++ -o Makefile Kulki.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I../Desktop/Qt/4.8.1/gcc/mkspecs/linux-g++ -I. -I../Desktop/Qt/4.8.1/gcc/include/QtCore -I../Desktop/Qt/4.8.1/gcc/include/QtGui -I../Desktop/Qt/4.8.1/gcc/include -I. -I.
LINK          = g++
LFLAGS        = -Wl,-O1 -Wl,-rpath,/home/juggler/QtSDK/Desktop/Qt/4.8.1/gcc/lib
LIBS          = $(SUBLIBS)  -L/home/juggler/QtSDK/Desktop/Qt/4.8.1/gcc/lib -lQtGui -L/home/juggler/QtSDK/Desktop/Qt/4.8.1/gcc/lib -L/usr/X11R6/lib -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /home/juggler/QtSDK/Desktop/Qt/4.8.1/gcc/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp \
		diagramscene.cpp \
		ball.cpp \
		ballnormal.cpp \
		ballkameleon.cpp \
		newgamedialog.cpp \
		balljoker.cpp \
		player.cpp moc_mainwindow.cpp \
		moc_diagramscene.cpp \
		moc_ball.cpp \
		moc_ballnormal.cpp \
		moc_ballkameleon.cpp \
		moc_newgamedialog.cpp \
		moc_balljoker.cpp \
		moc_ballskull.cpp \
		moc_ballbonus.cpp \
		moc_player.cpp \
		moc_ballclepsydra.cpp
OBJECTS       = main.o \
		mainwindow.o \
		diagramscene.o \
		ball.o \
		ballnormal.o \
		ballkameleon.o \
		newgamedialog.o \
		balljoker.o \
		player.o \
		moc_mainwindow.o \
		moc_diagramscene.o \
		moc_ball.o \
		moc_ballnormal.o \
		moc_ballkameleon.o \
		moc_newgamedialog.o \
		moc_balljoker.o \
		moc_ballskull.o \
		moc_ballbonus.o \
		moc_player.o \
		moc_ballclepsydra.o
DIST          = ../Desktop/Qt/4.8.1/gcc/mkspecs/common/unix.conf \
		../Desktop/Qt/4.8.1/gcc/mkspecs/common/linux.conf \
		../Desktop/Qt/4.8.1/gcc/mkspecs/common/gcc-base.conf \
		../Desktop/Qt/4.8.1/gcc/mkspecs/common/gcc-base-unix.conf \
		../Desktop/Qt/4.8.1/gcc/mkspecs/common/g++-base.conf \
		../Desktop/Qt/4.8.1/gcc/mkspecs/common/g++-unix.conf \
		../Desktop/Qt/4.8.1/gcc/mkspecs/qconfig.pri \
		../Desktop/Qt/4.8.1/gcc/mkspecs/modules/qt_webkit_version.pri \
		../Desktop/Qt/4.8.1/gcc/mkspecs/features/qt_functions.prf \
		../Desktop/Qt/4.8.1/gcc/mkspecs/features/qt_config.prf \
		../Desktop/Qt/4.8.1/gcc/mkspecs/features/exclusive_builds.prf \
		../Desktop/Qt/4.8.1/gcc/mkspecs/features/default_pre.prf \
		../Desktop/Qt/4.8.1/gcc/mkspecs/features/release.prf \
		../Desktop/Qt/4.8.1/gcc/mkspecs/features/default_post.prf \
		../Desktop/Qt/4.8.1/gcc/mkspecs/features/unix/gdb_dwarf_index.prf \
		../Desktop/Qt/4.8.1/gcc/mkspecs/features/warn_on.prf \
		../Desktop/Qt/4.8.1/gcc/mkspecs/features/qt.prf \
		../Desktop/Qt/4.8.1/gcc/mkspecs/features/unix/thread.prf \
		../Desktop/Qt/4.8.1/gcc/mkspecs/features/moc.prf \
		../Desktop/Qt/4.8.1/gcc/mkspecs/features/resources.prf \
		../Desktop/Qt/4.8.1/gcc/mkspecs/features/uic.prf \
		../Desktop/Qt/4.8.1/gcc/mkspecs/features/yacc.prf \
		../Desktop/Qt/4.8.1/gcc/mkspecs/features/lex.prf \
		../Desktop/Qt/4.8.1/gcc/mkspecs/features/include_source_dir.prf \
		Kulki.pro
QMAKE_TARGET  = Kulki
DESTDIR       = 
TARGET        = Kulki

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_newgamedialog.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: Kulki.pro  ../Desktop/Qt/4.8.1/gcc/mkspecs/linux-g++/qmake.conf ../Desktop/Qt/4.8.1/gcc/mkspecs/common/unix.conf \
		../Desktop/Qt/4.8.1/gcc/mkspecs/common/linux.conf \
		../Desktop/Qt/4.8.1/gcc/mkspecs/common/gcc-base.conf \
		../Desktop/Qt/4.8.1/gcc/mkspecs/common/gcc-base-unix.conf \
		../Desktop/Qt/4.8.1/gcc/mkspecs/common/g++-base.conf \
		../Desktop/Qt/4.8.1/gcc/mkspecs/common/g++-unix.conf \
		../Desktop/Qt/4.8.1/gcc/mkspecs/qconfig.pri \
		../Desktop/Qt/4.8.1/gcc/mkspecs/modules/qt_webkit_version.pri \
		../Desktop/Qt/4.8.1/gcc/mkspecs/features/qt_functions.prf \
		../Desktop/Qt/4.8.1/gcc/mkspecs/features/qt_config.prf \
		../Desktop/Qt/4.8.1/gcc/mkspecs/features/exclusive_builds.prf \
		../Desktop/Qt/4.8.1/gcc/mkspecs/features/default_pre.prf \
		../Desktop/Qt/4.8.1/gcc/mkspecs/features/release.prf \
		../Desktop/Qt/4.8.1/gcc/mkspecs/features/default_post.prf \
		../Desktop/Qt/4.8.1/gcc/mkspecs/features/unix/gdb_dwarf_index.prf \
		../Desktop/Qt/4.8.1/gcc/mkspecs/features/warn_on.prf \
		../Desktop/Qt/4.8.1/gcc/mkspecs/features/qt.prf \
		../Desktop/Qt/4.8.1/gcc/mkspecs/features/unix/thread.prf \
		../Desktop/Qt/4.8.1/gcc/mkspecs/features/moc.prf \
		../Desktop/Qt/4.8.1/gcc/mkspecs/features/resources.prf \
		../Desktop/Qt/4.8.1/gcc/mkspecs/features/uic.prf \
		../Desktop/Qt/4.8.1/gcc/mkspecs/features/yacc.prf \
		../Desktop/Qt/4.8.1/gcc/mkspecs/features/lex.prf \
		../Desktop/Qt/4.8.1/gcc/mkspecs/features/include_source_dir.prf \
		/home/juggler/QtSDK/Desktop/Qt/4.8.1/gcc/lib/libQtGui.prl \
		/home/juggler/QtSDK/Desktop/Qt/4.8.1/gcc/lib/libQtCore.prl
	$(QMAKE) -spec ../Desktop/Qt/4.8.1/gcc/mkspecs/linux-g++ -o Makefile Kulki.pro
../Desktop/Qt/4.8.1/gcc/mkspecs/common/unix.conf:
../Desktop/Qt/4.8.1/gcc/mkspecs/common/linux.conf:
../Desktop/Qt/4.8.1/gcc/mkspecs/common/gcc-base.conf:
../Desktop/Qt/4.8.1/gcc/mkspecs/common/gcc-base-unix.conf:
../Desktop/Qt/4.8.1/gcc/mkspecs/common/g++-base.conf:
../Desktop/Qt/4.8.1/gcc/mkspecs/common/g++-unix.conf:
../Desktop/Qt/4.8.1/gcc/mkspecs/qconfig.pri:
../Desktop/Qt/4.8.1/gcc/mkspecs/modules/qt_webkit_version.pri:
../Desktop/Qt/4.8.1/gcc/mkspecs/features/qt_functions.prf:
../Desktop/Qt/4.8.1/gcc/mkspecs/features/qt_config.prf:
../Desktop/Qt/4.8.1/gcc/mkspecs/features/exclusive_builds.prf:
../Desktop/Qt/4.8.1/gcc/mkspecs/features/default_pre.prf:
../Desktop/Qt/4.8.1/gcc/mkspecs/features/release.prf:
../Desktop/Qt/4.8.1/gcc/mkspecs/features/default_post.prf:
../Desktop/Qt/4.8.1/gcc/mkspecs/features/unix/gdb_dwarf_index.prf:
../Desktop/Qt/4.8.1/gcc/mkspecs/features/warn_on.prf:
../Desktop/Qt/4.8.1/gcc/mkspecs/features/qt.prf:
../Desktop/Qt/4.8.1/gcc/mkspecs/features/unix/thread.prf:
../Desktop/Qt/4.8.1/gcc/mkspecs/features/moc.prf:
../Desktop/Qt/4.8.1/gcc/mkspecs/features/resources.prf:
../Desktop/Qt/4.8.1/gcc/mkspecs/features/uic.prf:
../Desktop/Qt/4.8.1/gcc/mkspecs/features/yacc.prf:
../Desktop/Qt/4.8.1/gcc/mkspecs/features/lex.prf:
../Desktop/Qt/4.8.1/gcc/mkspecs/features/include_source_dir.prf:
/home/juggler/QtSDK/Desktop/Qt/4.8.1/gcc/lib/libQtGui.prl:
/home/juggler/QtSDK/Desktop/Qt/4.8.1/gcc/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec ../Desktop/Qt/4.8.1/gcc/mkspecs/linux-g++ -o Makefile Kulki.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/Kulki1.0.0 || $(MKDIR) .tmp/Kulki1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/Kulki1.0.0/ && $(COPY_FILE) --parents mainwindow.h diagramscene.h ball.h ballnormal.h ballkameleon.h newgamedialog.h balljoker.h ballskull.h ballbonus.h player.h ballclepsydra.h .tmp/Kulki1.0.0/ && $(COPY_FILE) --parents main.cpp mainwindow.cpp diagramscene.cpp ball.cpp ballnormal.cpp ballkameleon.cpp newgamedialog.cpp balljoker.cpp player.cpp .tmp/Kulki1.0.0/ && $(COPY_FILE) --parents newgamedialog.ui .tmp/Kulki1.0.0/ && (cd `dirname .tmp/Kulki1.0.0` && $(TAR) Kulki1.0.0.tar Kulki1.0.0 && $(COMPRESS) Kulki1.0.0.tar) && $(MOVE) `dirname .tmp/Kulki1.0.0`/Kulki1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/Kulki1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_mainwindow.cpp moc_diagramscene.cpp moc_ball.cpp moc_ballnormal.cpp moc_ballkameleon.cpp moc_newgamedialog.cpp moc_balljoker.cpp moc_ballskull.cpp moc_ballbonus.cpp moc_player.cpp moc_ballclepsydra.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_diagramscene.cpp moc_ball.cpp moc_ballnormal.cpp moc_ballkameleon.cpp moc_newgamedialog.cpp moc_balljoker.cpp moc_ballskull.cpp moc_ballbonus.cpp moc_player.cpp moc_ballclepsydra.cpp
moc_mainwindow.cpp: diagramscene.h \
		ball.h \
		ballnormal.h \
		ballkameleon.h \
		balljoker.h \
		ballskull.h \
		ballbonus.h \
		ballclepsydra.h \
		player.h \
		newgamedialog.h \
		mainwindow.h
	/home/juggler/QtSDK/Desktop/Qt/4.8.1/gcc/bin/moc $(DEFINES) $(INCPATH) mainwindow.h -o moc_mainwindow.cpp

moc_diagramscene.cpp: ball.h \
		ballnormal.h \
		ballkameleon.h \
		balljoker.h \
		ballskull.h \
		ballbonus.h \
		ballclepsydra.h \
		player.h \
		diagramscene.h
	/home/juggler/QtSDK/Desktop/Qt/4.8.1/gcc/bin/moc $(DEFINES) $(INCPATH) diagramscene.h -o moc_diagramscene.cpp

moc_ball.cpp: ball.h
	/home/juggler/QtSDK/Desktop/Qt/4.8.1/gcc/bin/moc $(DEFINES) $(INCPATH) ball.h -o moc_ball.cpp

moc_ballnormal.cpp: ball.h \
		ballnormal.h
	/home/juggler/QtSDK/Desktop/Qt/4.8.1/gcc/bin/moc $(DEFINES) $(INCPATH) ballnormal.h -o moc_ballnormal.cpp

moc_ballkameleon.cpp: ball.h \
		ballkameleon.h
	/home/juggler/QtSDK/Desktop/Qt/4.8.1/gcc/bin/moc $(DEFINES) $(INCPATH) ballkameleon.h -o moc_ballkameleon.cpp

moc_newgamedialog.cpp: player.h \
		diagramscene.h \
		ball.h \
		ballnormal.h \
		ballkameleon.h \
		balljoker.h \
		ballskull.h \
		ballbonus.h \
		ballclepsydra.h \
		newgamedialog.h
	/home/juggler/QtSDK/Desktop/Qt/4.8.1/gcc/bin/moc $(DEFINES) $(INCPATH) newgamedialog.h -o moc_newgamedialog.cpp

moc_balljoker.cpp: ball.h \
		balljoker.h
	/home/juggler/QtSDK/Desktop/Qt/4.8.1/gcc/bin/moc $(DEFINES) $(INCPATH) balljoker.h -o moc_balljoker.cpp

moc_ballskull.cpp: ball.h \
		ballskull.h
	/home/juggler/QtSDK/Desktop/Qt/4.8.1/gcc/bin/moc $(DEFINES) $(INCPATH) ballskull.h -o moc_ballskull.cpp

moc_ballbonus.cpp: ball.h \
		ballbonus.h
	/home/juggler/QtSDK/Desktop/Qt/4.8.1/gcc/bin/moc $(DEFINES) $(INCPATH) ballbonus.h -o moc_ballbonus.cpp

moc_player.cpp: player.h
	/home/juggler/QtSDK/Desktop/Qt/4.8.1/gcc/bin/moc $(DEFINES) $(INCPATH) player.h -o moc_player.cpp

moc_ballclepsydra.cpp: ball.h \
		ballclepsydra.h
	/home/juggler/QtSDK/Desktop/Qt/4.8.1/gcc/bin/moc $(DEFINES) $(INCPATH) ballclepsydra.h -o moc_ballclepsydra.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_newgamedialog.h
compiler_uic_clean:
	-$(DEL_FILE) ui_newgamedialog.h
ui_newgamedialog.h: newgamedialog.ui
	/home/juggler/QtSDK/Desktop/Qt/4.8.1/gcc/bin/uic newgamedialog.ui -o ui_newgamedialog.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp mainwindow.h \
		diagramscene.h \
		ball.h \
		ballnormal.h \
		ballkameleon.h \
		balljoker.h \
		ballskull.h \
		ballbonus.h \
		ballclepsydra.h \
		player.h \
		newgamedialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		diagramscene.h \
		ball.h \
		ballnormal.h \
		ballkameleon.h \
		balljoker.h \
		ballskull.h \
		ballbonus.h \
		ballclepsydra.h \
		player.h \
		newgamedialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

diagramscene.o: diagramscene.cpp diagramscene.h \
		ball.h \
		ballnormal.h \
		ballkameleon.h \
		balljoker.h \
		ballskull.h \
		ballbonus.h \
		ballclepsydra.h \
		player.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o diagramscene.o diagramscene.cpp

ball.o: ball.cpp ball.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ball.o ball.cpp

ballnormal.o: ballnormal.cpp ballnormal.h \
		ball.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ballnormal.o ballnormal.cpp

ballkameleon.o: ballkameleon.cpp ballkameleon.h \
		ball.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ballkameleon.o ballkameleon.cpp

newgamedialog.o: newgamedialog.cpp newgamedialog.h \
		player.h \
		diagramscene.h \
		ball.h \
		ballnormal.h \
		ballkameleon.h \
		balljoker.h \
		ballskull.h \
		ballbonus.h \
		ballclepsydra.h \
		ui_newgamedialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o newgamedialog.o newgamedialog.cpp

balljoker.o: balljoker.cpp balljoker.h \
		ball.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o balljoker.o balljoker.cpp

player.o: player.cpp player.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o player.o player.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_diagramscene.o: moc_diagramscene.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_diagramscene.o moc_diagramscene.cpp

moc_ball.o: moc_ball.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_ball.o moc_ball.cpp

moc_ballnormal.o: moc_ballnormal.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_ballnormal.o moc_ballnormal.cpp

moc_ballkameleon.o: moc_ballkameleon.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_ballkameleon.o moc_ballkameleon.cpp

moc_newgamedialog.o: moc_newgamedialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_newgamedialog.o moc_newgamedialog.cpp

moc_balljoker.o: moc_balljoker.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_balljoker.o moc_balljoker.cpp

moc_ballskull.o: moc_ballskull.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_ballskull.o moc_ballskull.cpp

moc_ballbonus.o: moc_ballbonus.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_ballbonus.o moc_ballbonus.cpp

moc_player.o: moc_player.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_player.o moc_player.cpp

moc_ballclepsydra.o: moc_ballclepsydra.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_ballclepsydra.o moc_ballclepsydra.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

